# Generated by Django 3.1.5 on 2021-05-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210422_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='4ZAGCQ', max_length=10),
        ),
    ]
