# Generated by Django 3.1.5 on 2021-05-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210502_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(default='Y5PXKT', max_length=10),
        ),
    ]
